name: openapi_client_generator
description: Parses an OpenAPI description to generate a Dart client for the described API.
version: 0.0.0-a1
# homepage: https://www.example.com

environment:
  sdk: ^3.0.0

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
